version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      JSONNET_VERSION: 0.18.0
    steps:
      - checkout
      - run: git clone https://github.com/ridebeam/grafonnet-lib
      - run: .circleci/setup-jsonnet.sh
      - run: PATH=$PATH:$(pwd) .circleci/build-all.sh

  fetch-and-publish-staging:
    docker:
      - image: cimg/base:2020.01
    environment:
      JSONNET_VERSION: 0.18.0
    steps:
      - checkout
      - run: git clone https://github.com/ridebeam/grafonnet-lib
      - run: .circleci/setup-jsonnet.sh
      - run: PATH=$PATH:$(pwd) ./update-gcp.sh "core" "http://grafana-staging.core.ridebeam.cloud" ${GRAFANA_STAGING_API_TOKEN}

  fetch-and-publish-core:
    docker:
      - image: cimg/base:2020.01
    environment:
      JSONNET_VERSION: 0.18.0
    steps:
      - checkout
      - run: git clone https://github.com/ridebeam/grafonnet-lib
      - run: .circleci/setup-jsonnet.sh
      - run: PATH=$PATH:$(pwd) ./update-gcp.sh "core" "https://grafana.core.ridebeam.cloud" ${GRAFANA_CORE_API_TOKEN}

  fetch-and-publish-devops:
    docker:
      - image: cimg/base:2020.01
    environment:
      JSONNET_VERSION: 0.18.0
    steps:
      - checkout
      - run: git clone https://github.com/ridebeam/grafonnet-lib
      - run: .circleci/setup-jsonnet.sh
      - run: PATH=$PATH:$(pwd) ./update-gcp.sh "devops" "https://grafana.devops.ridebeam.cloud" ${GRAFANA_API_TOKEN}

workflows:
  version: 2
  publish:
    jobs:
    - build:
        filters:
          branches:
            ignore: master
    - fetch-and-publish-staging:
        filters:
          branches:
            only: master
    - fetch-and-publish-core:
        filters:
          branches:
            only: master
    - fetch-and-publish-devops:
        filters:
          branches:
            only: master
