version: 2.1
jobs:
  fetch-and-publish:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: git clone https://github.com/ridebeam/grafonnet-lib
      - setup_remote_docker
      - run: docker create -v /usr/src/app --name tmp --entrypoint /bin/true bitnami/jsonnet
      - run: docker cp . tmp:/usr/src/app
      - run: docker run --volumes-from tmp -w /usr/src/app --entrypoint /bin/bash bitnami/jsonnet update.sh ${API_TOKEN}

workflows:
  version: 2
  publish:
    jobs:
    - fetch-and-publish:
        filters:
          branches:
            only: master
