// TODO: Make this queryable from Clickhouse.
// This is a list of cities that have alerts enabled.
[
  { id: 121, name: 'Seoul' },
  { id: 16, name: 'Brisbane', alerts: true },
  { id: 356, name: 'Daegu', alerts: true },
  { id: 612, name: 'Goyang-Paju', alerts: true },
  { id: 483, name: 'CheonanCity' },
  { id: 552, name: 'Cheongju' },
  { id: 12, name: 'Kuala Lumpur' },
  { id: 650, name: 'Gwangju' },
  { id: 13, name: 'Auckland' },
  { id: 416, name: 'Incheon' },
  { id: 370, name: 'ADLCity' },
  { id: 21, name: 'Canberra' },
  { id: 341, name: 'Seongnam-Suwon' },
  { id: 15, name: 'Wellington' },
  { id: 507, name: 'Busan' },
  { id: 349, name: 'Selangor' },
  { id: 553, name: 'Daejeon' },
  { id: 460, name: 'Townsville' },
  { id: 1118, name: 'Hobart' },
  { id: 891, name: 'Gunsan' },
  { id: 19, name: 'Sydney' },
  { id: 618, name: 'Gwangyang' },
  { id: 1425, name: 'Chuncheon' },
  { id: 1119, name: 'Launceston' },
  { id: 1121, name: 'Whangarei' },
  { id: 1096, name: 'Mackay' },
  { id: 1190, name: 'Esperance' },
  { id: 809, name: 'Palmerston North' },
  { id: 300, name: 'Bunbury' },
  { id: 580, name: 'Bangkok' },
  { id: 1519, name: 'Fethiye' },
  { id: 1529, name: 'Marmaris' },
  { id: 1036, name: 'PortDouglas' },
  { id: 994, name: 'Phuket' },
  { id: 1079, name: 'Rockingham' },
  { id: 1464, name: 'Bodrum' },
  { id: 1443, name: 'Pahang' },
  { id: 1462, name: 'Burnie' },
]
